# Generated by Django 4.1.6 on 2023-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_advert_advert_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
