# Generated by Django 4.1.6 on 2023-02-10 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_response_response_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
