# Generated by Django 4.1.6 on 2023-02-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_response_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_responses', to='portal.advert'),
        ),
    ]
