# Generated by Django 4.1.6 on 2023-02-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_advert_advert_category_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='category',
            new_name='advert_category',
        ),
    ]
