# Generated by Django 4.1.6 on 2023-02-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_rename_category_advert_advert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.category'),
        ),
    ]
