# Generated by Django 4.1.6 on 2023-02-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_advert_advert_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('TK', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД')], default='TK', max_length=2),
        ),
    ]
